name: Publish Docker images (GHCR)
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

permissions: {}

jobs:
  publish:
    name: Build and publish Docker images
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Publish Docker
        run: script/cibuild-publish-ghcr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
